# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-test # nama ini akan ditampilkan di actions pada github pages

on: # define event that can triger the workflow
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    # kopas saja si dari google github action postgres
     # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:15.2-alpine
        # Provide the password for postgres
        env:
          # ini tinggal salin dari Makefile
          POSTGRES_USER: root
          POSTGRES_PASSWORD: 21204444
          POSTGRES_DB: bank_mandiri
        # Set health checks to wait until postgres has started
        # memberitahu runner bagaimana caranya mengecek apakah postgres sudah berjalan dengan sukses atau tidak, jadi runner tahu kapan untuk memulai langkah selanjutnya di workflow. ini diperlukan karena kita perlu mengetes menjalankan ps terlebih dahulu sebelum melakukan tes transaksi" didalamnya 
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        # spesifi port yang kita ingin expose ke external host
        # ports:
        #   - 5432:5432

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
      id: go # hanya sebuah unik identifier dari step ini

    - name: Check out code into the Go module directiory
      uses: actions/checkout@v3

    - name: install migrate golang
    # | digunakan untuk membuat multiple line command
    # download migrate lalu unzip dan pindahkan ke usr/bin dan ubah namanya menjadi migrate
      run: |
       curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
       sudo mv migrate /usr/bin
       which migrate

    # setelah mengecek go, kita bisa melakukan migrate up
    - name: Jalankan migrasi up
      run: make migup

    - name: Test
      run: make test